title: <p align="center"> Mahendra Takwale </p>
description: 
<p align="center">
<br>
I am working Data Science, Data Protection and Analytics
<br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
